spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 150
        prepStmtCacheSqlLimit: 1024
        useServerPrepStmts: true
    initialization-mode: always
#    data: classpath:data.sql


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.hbm2ddl.import_files: data.sql
    hibernate:
      ddl-auto: update


